const S={user:null,scripts:[],execs:[],isBrowser:true};

function detect(){const e=['syn','krnl','fluxus','getexecutorname','getgc','getconnections'];S.isBrowser=!e.some(x=>typeof window[x]!=='undefined');if(S.isBrowser){const b=document.getElementById('protect');b.style.display='block';setTimeout(()=>b.style.display='none',5000);}}

function signIn(){toast('Connecting to Roblox...','info');setTimeout(()=>{S.user={id:'3255755288279625071',name:'Zurai02',avatar:'Z'};localStorage.setItem('zp_user',JSON.stringify(S.user));updateAuth();loadScripts();toast('Signed in!','ok');},1200);}
function signOut(){S.user=null;localStorage.removeItem('zp_user');S.scripts=[];updateAuth();render();updateStats();toast('Signed out','info');}
function updateAuth(){const L=document.getElementById('authLogin'),U=document.getElementById('userInfo');if(S.user){L.style.display='none';U.style.display='flex';document.getElementById('uName').textContent=S.user.name;document.getElementById('uId').textContent='ID: '+S.user.id;document.getElementById('avatar').textContent=S.user.avatar;}else{L.style.display='block';U.style.display='none';}}

function openModal(){if(!S.user){toast('Sign in first!','err');return;}document.getElementById('modal').classList.add('active');document.getElementById('sName').focus();}
function closeModal(){document.getElementById('modal').classList.remove('active');['sName','sDesc','sCode'].forEach(x=>document.getElementById(x).value='');document.getElementById('sLang').value='lua';}
function saveScript(){const n=document.getElementById('sName').value.trim(),d=document.getElementById('sDesc').value.trim(),l=document.getElementById('sLang').value,c=document.getElementById('sCode').value.trim();if(!n||!c){toast('Name and code required!','err');return;}S.scripts.push({id:Date.now().toString(36)+Math.random().toString(36).slice(2),name:n,desc:d||'No description',lang:l,code:c,execs:0,last:null,owner:S.user.id,output:''});save();render();updateStats();closeModal();toast('Script saved!','ok');}
function delScript(id){if(!confirm('Delete this script?'))return;S.scripts=S.scripts.filter(s=>s.id!==id);save();render();updateStats();toast('Deleted','info');}
function editScript(id){const s=S.scripts.find(x=>x.id===id);if(!s)return;document.getElementById('sName').value=s.name;document.getElementById('sDesc').value=s.desc;document.getElementById('sLang').value=s.lang;document.getElementById('sCode').value=s.code;S.scripts=S.scripts.filter(x=>x.id!==id);openModal();}

function runScript(id){const s=S.scripts.find(x=>x.id===id);if(!s)return;if(S.isBrowser){document.getElementById('protect').style.display='block';setTimeout(()=>document.getElementById('protect').style.display='none',5000);toast('⚠️ Protected by Zurai02 Productions — Browser execution blocked','err');logExec(id,false,'Browser blocked');return;}

let output='';let success=true;try{if(s.lang==='luau'){output=executeLuau(s.code);}else if(s.lang==='lua'){output=executeLua(s.code);}else{output='Unknown language: '+s.lang;}}catch(e){output='Error: '+e.message;success=false;}

s.execs++;s.last=new Date().toISOString();s.output=output;logExec(id,success,success?'Executed':'Error: '+output);save();updateStats();render();toast(success?'Executed! ('+s.execs+' total)':'Execution failed',success?'ok':'err');}

function executeLuau(code){const lines=code.split('\n');const out=[];let inBlock=false,blockDepth=0;lines.forEach((line,idx)=>{const t=line.trim();if(!t||t.startsWith('--')){if(t.startsWith('--'))out.push('[comment] '+t);return;}if(t.startsWith('local ')){const m=t.match(/local\s+(\w+)\s*=\s*(.+)/);if(m)out.push('[Luau] Declared '+m[1]);else out.push('[Luau] local declaration');}else if(t.startsWith('function')||t.startsWith('local function')){out.push('[Luau] Function defined');inBlock=true;blockDepth=1;}else if(t==='end'){if(inBlock){blockDepth--;if(blockDepth<=0){inBlock=false;out.push('[Luau] Block ended');}}else out.push('[Luau] end');}else if(t.startsWith('if ')){out.push('[Luau] If statement');blockDepth++;}else if(t.startsWith('for ')||t.startsWith('while ')){out.push('[Luau] Loop start');blockDepth++;}else if(t.startsWith('print')){const m=t.match(/print\s*\((.+)\)/);if(m){const args=m[1].split(',').map(a=>a.trim().replace(/["']/g,''));out.push('[Luau] >> '+args.join(' '));}else out.push('[Luau] print()');}else if(t.startsWith('game:')||t.startsWith('workspace')||t.startsWith('Players:')){out.push('[Luau] Roblox API: '+t.substring(0,40));}else if(t.startsWith('require')){out.push('[Luau] Module required');}else{out.push('[Luau] '+t.substring(0,50));}});return out.join('\n')||'[Luau execution trace completed]';}

function executeLua(code){const lines=code.split('\n');const out=[];lines.forEach(line=>{const t=line.trim();if(!t||t.startsWith('--')){if(t.startsWith('--'))out.push('[comment] '+t);return;}if(t.startsWith('local ')){const m=t.match(/local\s+(\w+)\s*=\s*(.+)/);if(m)out.push('[Lua] Declared '+m[1]);else out.push('[Lua] local declaration');}else if(t.startsWith('function')){out.push('[Lua] Function defined');}else if(t==='end'){out.push('[Lua] end');}else if(t.startsWith('if ')){out.push('[Lua] If statement');}else if(t.startsWith('for ')||t.startsWith('while ')){out.push('[Lua] Loop start');}else if(t.startsWith('print')){const m=t.match(/print\s*\((.+)\)/);if(m){const args=m[1].split(',').map(a=>a.trim().replace(/["']/g,''));out.push('[Lua] >> '+args.join(' '));}else out.push('[Lua] print()');}else{out.push('[Lua] '+t.substring(0,50));}});return out.join('\n')||'[Lua execution trace completed]';}

function logExec(sid,ok,msg){S.execs.push({sid,t:new Date().toISOString(),ok,msg,env:S.isBrowser?'browser':'executor'});save();}

function render(){const g=document.getElementById('scriptGrid'),e=document.getElementById('empty');if(!S.scripts.length){g.innerHTML='';e.style.display='block';return;}e.style.display='none';g.innerHTML=S.scripts.map(s=>{const ic=s.lang==='luau'?'🔷 Luau (.lz)':'🟢 Lua (.lua)';const le=s.last?new Date(s.last).toLocaleString():'Never';const out=s.output?`<div class="output active">${esc(s.output)}</div>`:'';return`<div class="card"><div class="card-head"><div class="card-name">${esc(s.name)}</div><div class="card-lang">${ic}</div></div><div class="card-desc">${esc(s.desc)}</div><div class="card-meta"><span>▶️ ${s.execs}</span><span>🕐 ${le}</span></div><div class="card-actions"><button class="run" onclick="runScript('${s.id}')">▶️ Run</button><button class="edit" onclick="editScript('${s.id}')">✏️ Edit</button><button class="del" onclick="delScript('${s.id}')">🗑️</button></div>${out}</div>`;}).join('');}

function updateStats(){const te=S.scripts.reduce((a,s)=>a+s.execs,0),tb=S.execs.filter(e=>!e.ok).length,tl=S.execs.length?new Date(S.execs[S.execs.length-1].t).toLocaleTimeString():'Never';anim('tExec',te);anim('tScript',S.scripts.length);anim('tBlock',tb);document.getElementById('tLast').textContent=tl;}
function anim(id,end){const el=document.getElementById(id),st=parseInt(el.textContent)||0;if(st===end)return;const d=800,step=Math.max(30,Math.floor(d/Math.abs(end-st)));let cv=st;const t=setInterval(()=>{cv+=st<end?1:-1;el.textContent=cv;if(cv===end)clearInterval(t);},step);}

function save(){try{localStorage.setItem('zp_scripts',JSON.stringify(S.scripts));localStorage.setItem('zp_execs',JSON.stringify(S.execs));}catch(e){}}
function load(){try{const u=localStorage.getItem('zp_user'),sc=localStorage.getItem('zp_scripts'),ex=localStorage.getItem('zp_execs');if(u){S.user=JSON.parse(u);updateAuth();}if(sc)S.scripts=JSON.parse(sc);if(ex)S.execs=JSON.parse(ex);render();updateStats();}catch(e){}}
function loadScripts(){render();updateStats();}

function esc(t){const d=document.createElement('div');d.textContent=t;return d.innerHTML;}
function toast(msg,type='info'){const c=document.getElementById('toasts'),t=document.createElement('div');t.className='toast '+(type==='ok'?'ok':type==='err'?'err':'');t.innerHTML=(type==='ok'?'✅':type==='err'?'❌':'ℹ️')+' '+esc(msg);c.appendChild(t);setTimeout(()=>{t.style.opacity='0';t.style.transform='translateX(100%)';setTimeout(()=>t.remove(),300);},3500);}

document.addEventListener('DOMContentLoaded',()=>{detect();load();document.getElementById('modal').addEventListener('click',e=>{if(e.target===document.getElementById('modal'))closeModal();});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();if(e.ctrlKey&&e.key==='n'){e.preventDefault();openModal();}});});

window.openModal=openModal;window.closeModal=closeModal;window.saveScript=saveScript;window.delScript=delScript;window.runScript=runScript;window.editScript=editScript;window.signIn=signIn;window.signOut=signOut;
